name: Java CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Unit Tests
        run: mvn --batch-mode --update-snapshots verify "-Dtest=br.com.concessionaria.unidade.*Test"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          flags: unidade

      - name: Run Integration Tests
        run: mvn --batch-mode --update-snapshots verify "-Dtest=br.com.concessionaria.integracao.*Test"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          flags: integracao