name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:  
      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Tests
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
